language: java

before_install:
  - touch .ojdbc6.exclude

before_script:
  - mysql -uroot -e 'SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED'
  - mysql -e 'show variables;'
  - mysql -e 'create database testsupport;'
  - ls -a .*.exclude

script:
  - mvn clean test -Djixture.sample.database.type=mysql

branches:
  only:
    - master